<?php

/**
 * pageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('page');
    }
}